# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        cache: true


    - name: Install dependencies
      run: go mod vendor

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: 'latest'

  test:
    needs: golangci
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        cache: true

    - uses: actions/checkout@v3

    - name: Install dependencies
      run: go mod vendor

    - name: Test
      run: go test -v ./...

  build:
    needs: [golangci, test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        cache: true

    - name: Install dependencies
      run: go mod vendor

    - name: Build
      run: go build -v ./...
